title: Islands Corporation
description: Islands Corporation, “We are the Destination!”. Welcome to the Official Website of Islands Corporation! Our platform is an upcoming ROBLOX Hotel experience helping to provide an all-inclusive and interactive environment. We hope to create a welcoming community filled with those who are interested in meeting with new people, and those who may just join for fun!
baseurl: "/"
url: "https://zimo-gu.github.io/islandscorp/"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Group":
    - "https://www.roblox.com/groups/32389380/Islands-Corporation#!/about"
  "Discord":
    - "https://discord.gg/jSFcXBBYHZ"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
